Co-authored-by: nothatcreative5 <nothatcreative5@users.noreply.github…
Star-Academy/Summer1401-SE-Team08 pull request #1
Opened 2022-07-20 21:03 UTC by nothatcreative5

Clean Code

2022-07-22 06:32 UTC, BozorgmehrZia requested changes

2022-07-22 06:32 UTC, BozorgmehrZia commented on src/main/java/Main.java
>          System.out.println((endTime-startTime)/1e9);
چرا زمانش رو اندازه گرفتین؟

2022-07-22 06:32 UTC, BozorgmehrZia commented on src/main/java/Main.java
>          try {
extract method

2022-07-22 06:32 UTC, BozorgmehrZia commented on src/main/java/Stemmer.java
> +//import java.util.stream.Collectors;
کد کامنت شده نباید باشه

2022-07-22 06:32 UTC, BozorgmehrZia commented on src/main/java/Stemmer.java
> +        // return tokens.stream()
کد کامنت شده نباید باشه

2022-07-22 10:43 UTC, BozorgmehrZia commented
و اینکه اگه کلاسایی مثل file reader و tokenizer (بسته به معماری که خودتون صلاح میدونین) interface شون رو بسازین و از اون جای خود کلاس استفاده کنین که اصول سالید هم رعایت بشن بهتره البته این کار اجباری نیست ولی اگه انجام بدین بهتره.

2022-07-23 12:42 UTC, nothatcreative5 commented on src/main/java/Main.java
>          System.out.println((endTime-startTime)/1e9);
خواستیم مثل گوگل بعد هر query زمان صرف شده هم نشون بدیم.

2022-07-23 12:55 UTC, BozorgmehrZia requested changes

2022-07-23 12:55 UTC, BozorgmehrZia commented on src/main/java/FileReader.java
>      public static String readFile(File file) throws Exception{
contents اگه stringbuilder باشه بهتره

2022-07-23 12:55 UTC, BozorgmehrZia commented on src/main/java/Main.java
> +
اینتر اضافه پاک بشه

2022-07-23 12:55 UTC, BozorgmehrZia commented on src/main/java/Stemmer.java
> +
اینتر اضافه پاک بشه

2022-07-23 12:55 UTC, BozorgmehrZia commented on src/main/java/Tokenizer.java
>          contents = contents.toUpperCase();
دوتا رو یکی کنین

2022-07-23 12:55 UTC, BozorgmehrZia commented
کانفلیکتا یادتون نره

2022-07-23 14:23 UTC, Taha-Alikhani commented
pom.xml is a maven-related file and should be added to .gitignore

2022-07-23 14:29 UTC, Taha-Alikhani requested changes
Your code lacks comments, even though the algorithm is quite easy to understand, it's good to build a habit of commenting your codes.

2022-07-23 19:17 UTC, Taha-Alikhani approved these changes

2022-07-24 04:27 UTC, BozorgmehrZia commented on src/main/java/Main.java
>          System.out.println((endTime-startTime)/1e9);
چیز باحالیه ولی چون توی داک خواسته نشده نمیخواد انجامش بدین

2022-07-24 04:31 UTC, BozorgmehrZia approved these changes
کانفلیکتا یادتون نره

2022-07-24 06:34 UTC, merged