C# Average program.
Star-Academy/Summer1401-SE-Team08 pull request #2
Opened 2022-07-25 09:48 UTC by nothatcreative5

2022-07-25 12:08 UTC, BozorgmehrZia requested changes

2022-07-25 12:08 UTC, BozorgmehrZia commented on Phase03/Controller.cs
> +		return students.Select(x => new {
x یا student باشه یا حداقل s

2022-07-25 12:08 UTC, BozorgmehrZia commented on Phase03/FileReader.cs
> +    return JsonSerializer.Deserialize<List<Student>>(fileInput);
این خلاف اصل single responsibility ه
الان این کلاس هم داره از فایل میخونه هم داره دیسریالایز میکنه

2022-07-25 15:01 UTC, BozorgmehrZia requested changes

2022-07-25 15:01 UTC, BozorgmehrZia commented on Phase03/Controller.cs
> +using System;
using اضافی پاک بشه

2022-07-25 15:01 UTC, BozorgmehrZia commented on Phase03/Controller.cs
> +	public List<Student> students {get; set;}
این و پایینیش اسمشون مطابق استاندارد c# نیستن

2022-07-25 15:01 UTC, BozorgmehrZia commented on Phase03/Program.cs
> +  public static string StudentJsonFileAddress = "./Data/students.json";
این دوتا const بشن
ضمنا آدرسشون غلطه

2022-07-25 15:01 UTC, BozorgmehrZia commented on Phase03/Program.cs
> +    var controller = new Controller();
از object initializer استفاده کنین
new Controller{
      students = students,
      scores = scores
}

2022-07-25 15:01 UTC, BozorgmehrZia commented on Phase03/Student.cs
> +    public class Student {
فاصله هاش درست نیست

2022-07-25 17:22 UTC, Taha-Alikhani requested changes
Comments pls :)

2022-07-25 17:22 UTC, Taha-Alikhani commented on Phase03/Program.cs
> +using System.IO;
Remove unused imports

2022-07-25 17:22 UTC, Taha-Alikhani commented on Phase03/Score.cs
> +    public float Score {get; init;}
نمرات ممکن نیست تغییر کنن؟
(just asking)

2022-07-25 17:22 UTC, Taha-Alikhani commented on Phase03/FileReader.cs
> +    var fileInput = File.ReadAllText(fileAddress);
Null-case not handled (i.e fileNotFound)

2022-07-26 07:48 UTC, RAAvenger reviewed
سلام 
خسته نباشید
تغییرات ایین برنچ خیلی زیادن
اصلاحات مربوط به مسیر فایل‌ها رو میتونستید روی یه برنچ دیگه انجام بدید و مرج کنید
موقع نامگذاری هم به معنا دادن اسامی دقت کنید

2022-07-26 07:48 UTC, RAAvenger commented on Phase03/Controller.cs
> +	public List<string> GetTopStudents(int n){
متغییر یک حرفی تا جای ممکن استفاده نشه

2022-07-26 07:48 UTC, RAAvenger commented on Phase03/Controller.cs
> +					x => "FirstName: " + x.St.FirstName + ", LastName: " + x.St.LastName + ", Average: " + x.Average).ToList();
برای بهبود عملکردی و خوانایی بهتره از [string interpolation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated) استفاده کنید

2022-07-26 07:48 UTC, RAAvenger commented on Phase03/Controller.cs
> +public class Controller {
اسم گذاری جالبی نیست
با توجه به اینکه قراره کلاستون single responsible باشه از اون responsibility کلاس برای نامگذاریش کمک بگیرید

2022-07-26 07:48 UTC, RAAvenger commented on Phase03/FileReader.cs
> +class FileReader{
این کلاس به حداقل دوتا چیز وابسته هست
وابستگی‌هاش رو کمتر کنید
1 خوندن فایل: در صورتی که ازتون خواسته شد به جای فایل از stream یا هر منبع دیگه‌ای بخونید مجبور میشید برگردید این کلاس رو دستکاری کنید
2 قالب فایل: اگر بجای json ورودی xml یا هر فرمت دیگه ای بشه مجبورید برگردید و این کلاس رو دستکاری کنید

2022-07-26 07:48 UTC, RAAvenger commented on Phase03/Student.cs
> +    public class Student {
این میتونه record باشه

2022-07-26 15:00 UTC, Taha-Alikhani approved these changes

2022-07-26 15:00 UTC, Taha-Alikhani commented on Phase03/src/Program.cs
> +	static void Main()
Main is too long and does more than 1 job

2022-07-26 15:00 UTC, Taha-Alikhani commented on Phase03/src/StudentManagement/StudentManager.cs
> +	{
Can be broken down into multiple functions (?)

2022-07-27 03:48 UTC, BozorgmehrZia approved these changes
اگه یه کلاس جدا واسه خوندن فایل میزاشتین یدونه دیگم واسه دیسریالایز کردن و هر کدوم یه اینترفیسی رو implement میکردن تمیز تر بود ولی اینم اوکیه

2022-07-27 07:08 UTC, aliEm2001 requested changes

2022-07-27 07:08 UTC, aliEm2001 commented on Phase03/src/StudentManagement/StudentManager.cs
> +				.Select(x => $"FirstName: {x.St.FirstName}, LastName: {x.St.LastName}, Average: {x.Average}").ToList();
این قسمت داره بخش اعظمی از لاجیک برنامه رو هندل میکنه و پیچیده شده، بهتره که به قسمتای کوچکتری شکسته بشه

2022-07-27 07:08 UTC, aliEm2001 commented on Phase03/src/Program.cs
> +	}
بهتره که بجای عدد 3 ، از magic number استفاده بشه

2022-07-27 07:13 UTC, aliEm2001 commented on Phase03/src/Program.cs
> +	}
const int ...

2022-07-27 09:54 UTC, smhh22 commented on Phase03/src/StudentManagement/StudentManager.cs
> +				.Select(x => $"FirstName: {x.St.FirstName}, LastName: {x.St.LastName}, Average: {x.Average}").ToList();
مثلا اون select آخری رو میشد به جاش توی خود کلاس Student، ToString رو override کرد.

2022-07-27 10:04 UTC, smhh22 requested changes

2022-07-27 10:04 UTC, smhh22 commented on Phase03/src/StudentManagement/StudentManager.cs
> +				.Select(x => $"FirstName: {x.St.FirstName}, LastName: {x.St.LastName}, Average: {x.Average}").ToList();
کلا قابل فهم بودنش کمه این تیکه. ایده‌ای ندارم کاریش میشه کرد یا نه.
ساده‌ترین راهش اینه که یه کامنت ریز بذارید که چه اتفاقی داره میفته.

2022-07-27 10:04 UTC, smhh22 commented on Phase03/src/Program.cs
> +			grades = JsonSerializer.Deserialize<List<Grade>>(File.ReadAllText(GradesFileAddress));
یه ایده‌ای که میشه زد اینه که کلا بیایم یه Interface بزنیم برای دیسریالایز کردن که اگه نیازی شد که مثلا ورودی به فرمت دیگه‌ای داده بشه راحت بشه این فیچرو اضافه کرد.
ولی مهم نیست خیلی، با آداپتر هم هندل میشه فکر کنم.

2022-07-27 12:18 UTC, RAAvenger commented on Phase03/src/Program.cs
> +	public static string StudentsFileAddress = "../Data/students.json";
const

2022-07-27 12:18 UTC, RAAvenger approved these changes

2022-07-27 13:39 UTC, merged