Unit test
Star-Academy/Summer1401-SE-Team08 pull request #3
Opened 2022-07-27 22:56 UTC by KhosroMoeini

Phase04 - Unit Test

2022-07-28 03:52 UTC, BozorgmehrZia requested changes

2022-07-28 03:52 UTC, BozorgmehrZia commented on Phase04/OperatorTester.cs
> +using SimpleCalculator.Business;
این کلاس خیلی تستاش زیادن
اگه چنتا کلاسش کنی بهتره

2022-07-28 03:52 UTC, BozorgmehrZia commented on Phase04/OperatorTester.cs
> +    public void SumEnumTet(OperatorEnum fParam) {
fParam خیلی خوب نیس اسمش

2022-07-28 03:52 UTC, BozorgmehrZia commented on Phase04/OperatorTester.cs
> +        //act
این کامنتای act , assert بنظرم نیازی نیستن

2022-07-29 07:09 UTC, BozorgmehrZia requested changes

2022-07-29 07:09 UTC, BozorgmehrZia commented on Phase04/CalculatorTester.cs
> +        Calculator calculator = new Calculator(provider_sub.Object);
var

2022-07-29 07:09 UTC, BozorgmehrZia commented on Phase04/CalculatorTester.cs
> +        int actual = calculator.Calculate(firstOperand, secondOperand, OperatorEnum.sum);
var

2022-07-29 07:09 UTC, BozorgmehrZia commented on Phase04/ExceptionTester.cs
> +        Action act = () => this._sumOperator.Calculate(firstOperand, secondOperand);
var

2022-07-29 07:09 UTC, BozorgmehrZia commented on Phase04/OperatorTester.cs
> +        int actual = this._multiplyOperator.Calculate(firstOperand, secondOperand);
var

2022-07-29 09:24 UTC, BozorgmehrZia approved these changes

2022-07-29 10:59 UTC, Taha-Alikhani approved these changes
calculator ui can be tested as well (if you wanted to)

2022-07-29 11:04 UTC, Taha-Alikhani commented
Press ctrl+shift+I (linux) or alt+shift+f (windows) :)

2022-07-30 10:10 UTC, M79Montazer approved these changes

2022-07-30 10:10 UTC, M79Montazer commented on Phase04/CalculatorTester.cs
> +    public void CalculatorAdditionTest(int firstOperand, int secondOperand, int expected) {
قرارداد های رایج نام گذاری برای تست متودها رعایت نشده اند.

2022-07-30 10:10 UTC, M79Montazer commented on Phase04/CalculatorTester.cs
> +        var calculator = new Calculator(provider_sub.Object);
_calculator is already initialized and can be used here.
the is no need for new calculator.

2022-08-01 05:54 UTC, RAAvenger requested changes
سلام
خسته نباشید
ساختار پروژه رو اصلاح کنید

2022-08-01 05:54 UTC, RAAvenger commented on Phase04/SimpleCalculator-master/SimpleCalculator.Business/OperatorBusiness/Operators/SumOperator.cs
> +    internal class SumOperator : IOperator
همه `Operator`ها `public` بشن

2022-08-01 05:54 UTC, RAAvenger commented on Phase04/Phase04.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
ساختار پروژه مشکل داره
ساختار درست:


phase04
-.gitignore
-... 
-simpleCalculator
--.sln
--SimpleCalculator
---.csproj
---ui codes
--SimpleCalculator.Business
---.csproj
---main logic codes
--SimpleCalculator.Tests
---.csproj
---tests

2022-08-01 05:54 UTC, RAAvenger commented on Phase04/OperatorTester.cs
> +using SimpleCalculator.Business;
هر `Operator` معادل کلاس خودش یه کلاس تست داشته باشه

2022-08-01 05:54 UTC, RAAvenger commented on Phase04/CalculatorTester.cs
> +        Assert.Equal(actual, expected);
از fluentAssertion استفاده کنید

2022-08-01 05:54 UTC, RAAvenger commented on Phase04/CalculatorTester.cs
> +    public void CalculatorAdditionTest(int firstOperand, int secondOperand, int expected) {
کامنتای 
//Arrange
//Act
//Assert 
رو هم بذارید

2022-08-01 05:54 UTC, RAAvenger commented on Phase04/CalculatorTester.cs
> +    [InlineData(-3,0,-3)]
این دوتا ورودی حالت خاصی رو تست میکنن؟
اگر نه اضافی هستن

2022-08-03 18:23 UTC, RAAvenger reviewed
سلام
خسته نباشید
چندتا ایراد جزئی هست
رفع کنید

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/CalculatorTest.cs
> +    [InlineData(-3,0,-3)]
کلا تست کیسایی که مزیتی ندارن پاک بشن

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/CalculatorTest.cs
> +        providerSub.Setup(x => x.GetOperator(OperatorEnum.Sum)).Returns(new SumOperator());
اوپراتوری که توی Returns یه اوپراتور ماک شده باشه

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/CalculatorTest.cs
> +    }
اگر توی تست اول به درستی از ماک استفاده بشه هیچ نیازی به این تستا نیست

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/CalculatorTest.cs
> +        var providerSub = new Mock<IOperatorProvider>();
NSubstitude

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/DivisionOperatorTest.cs
> +    }
چرا OperatorProvider رو دارین تست میکنین؟
فقط DivisionOperator تست بشه

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/DivisionOperatorTest.cs
> +        // Act
اگر میبینید توی منطق تستتون Arrange ندارید یعنی تست مشکل داره

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/ExceptionTest.cs
> +    }
چرا این رو بین تستای کلاس OperatorProvider ننوشتید؟

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/ExceptionTest.cs
> +    }
بررسی این حالت‌ها مزیت خاصی نداره مگر اینکه بشه با کمک تستا حالتای مرزی رو شناسایی کرد
بعد هم همه تستای اینجا باید به قسمت مربوط به تستای کلاسایی که دارن تست میشن منتقل بشن

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/MultiplyOperatorTest.cs
> +namespace Phase04.SimpleCalculator.Tests;
دلیل تغییر namespace و اضافه شدن Phase04 چیه؟

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/SumOperatorTest.cs
> +    [InlineData(-11,-12,-23)]
کلی تست اضافی که مزیتی ندارن

2022-08-03 18:23 UTC, RAAvenger commented on Phase04/SimpleCalculator/UiManager.cs
> +        private static readonly Dictionary<string, OperatorEnum> SOperatorSigns = new()
private static => s_fieldName

2022-08-03 19:20 UTC, nothatcreative5 commented on Phase04/SimpleCalculator.Tests/MultiplyOperatorTest.cs
> +namespace Phase04.SimpleCalculator.Tests;
به دلیل ساختار پروژه، Rider این پیشنهاد رو داد.

2022-08-03 19:47 UTC, nothatcreative5 commented on Phase04/SimpleCalculator/UiManager.cs
> +        private static readonly Dictionary<string, OperatorEnum> SOperatorSigns = new()
این فیلد رو اصلا ما ننوشتیم و clone شده. اسم هم اگه عوض کنم Rider مخالفت میکنه.

2022-08-06 10:02 UTC, RAAvenger approved these changes
سلام
خسته نباشید

2022-08-06 10:02 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/CalculatorTest.cs
> +        var calculator = new Calculator(provider);
میتونه توی arrange باشه

2022-08-06 10:02 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/CalculatorTest.cs
> +    }
همون تست اولی اینا رو هم پوشش میده

2022-08-06 10:02 UTC, RAAvenger commented on Phase04/SimpleCalculator.Tests/CalculatorTest.cs
> +        sumOperator.Calculate(1, 23).Returns(24);
به جای عدد هاردکد شده متغییر بگیرید که اگر یه وقتی نیاز به تغییر بود یا خواستید به جای factبیاید theory  بنویسید راحتتر باشید

2022-08-06 13:44 UTC, aryajalali approved these changes

2022-08-06 13:48 UTC, merged