Tdd
Star-Academy/Summer1401-SE-Team08 pull request #4
Opened 2022-07-30 18:56 UTC by nothatcreative5

Initial Pull Request

2022-07-31 11:56 UTC, BozorgmehrZia requested changes
اسم توابع تست درست بشن مطابق همون چیزی که توی کارگاه گفته شده
و اینترفیسا توی یه پوشه جدا به اسم Abstraction باشن

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/FileReaderTest.cs
> +    private readonly FileReader _fileReader;
باید interface ش باشه و بعد ماکش کنین

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/FileReaderTest.cs
> +        var path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.FullName +
از path.combine استفاده کنین بهتره

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/FileReaderTest.cs
> +        var actual = _fileReader.ReadFolder(path);
یه پوشه موقت بساز و فایلا رو ایجاد کن و بعد ران شدن تستا پاکش کن

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/SearchEngineTester.cs
> +    private ISearchEngine _searchEngine;
این دوتا readonly باشن

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/TokenizerTester.cs
> +        IEnumerable<string> expected = new List<string>()
متغیرا var باشن

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/DictionaryExtensionMethods.cs
> +    public static void Merge<TKey, TValue>(this Dictionary<TKey, TValue> me, Dictionary<TKey, TValue> merge)
اسم ورودیا درست بشه

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/DictionaryExtensionMethods.cs
> +public static class DictionaryExtensionMethods
تاجای ممکن از کدای آماده استفاده کنین

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/InvertedIndex.cs
> +        SearchEngine engine = new SearchEngine();
var

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/InvertedIndex.cs
> +    public static HashSet<string> Search(string query)
اسمش دقیقتر باشه

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/InvertedIndex.cs
> +        var handler = new QueryHandler(engine);
اینا رو اگه قرار بود لوکال باشن چرا پش اینترفیس نوشتین؟
باید همه اینترفیس باشن و توی کانستراکتور initialize شن

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/Query.cs
> +            switch (token.GetTokenType())
switch case سینتکس جدید

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/QueryHandler.cs
> +    private SearchEngine _engine;
اینترفیس باشه و readonly

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/SearchEngine.cs
> +    public HashSet<string> Search(string word)
اسم تابع بهتر بشه

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/TokenType.cs
> +        } else if (token.StartsWith("-"))
else نمیخاد
if هم خط بعدی باشه

2022-07-31 11:56 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/Tokenizer.cs
> +        SetMode(mode);
چرا تابع جدا گذاشتین؟

2022-08-04 08:30 UTC, BozorgmehrZia requested changes
کامنتای قبلیم رو لطفا برطرف کن

2022-08-04 08:30 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/FileReaderTest.cs
> +﻿// using InvertedIndex.Abstraction;
این چرا کامنته؟

2022-08-06 10:53 UTC, RAAvenger reviewed
سلام
خسته نباشید
یه سری اصلاحات کوچیک هستن که میتونید داشته باشید

2022-08-06 10:53 UTC, RAAvenger commented on Phase05/InvertedIndex.Test/QueryHandlerTest.cs
> +        _docIdSet = new Dictionary<string, List<string>>()
میشه 
```
new Dictionary<string, List<string>>()
```
رو به 
```
new()
```
خلاصه کرد

2022-08-06 10:53 UTC, RAAvenger commented on Phase05/InvertedIndex.Test/ReadFolderTest/2.txt
> +b
این فایلا رو توی یه پوشه مشخص بذارید بهتره

2022-08-06 10:53 UTC, RAAvenger commented on Phase05/InvertedIndex.Test/FileReaderTest.cs
> +//         var actual = _fileReader.ReadFolder(path);
اگر میخواید یه تست خوب بنویسید پیشنهاد میکنم فایلا رو موقع اجرای تست (Arrange) بسازید.
بعد برای پاک کردنشون هم از پترن [idisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=net-6.0) استفاده کنید

2022-08-06 10:53 UTC, RAAvenger commented on Phase05/InvertedIndex/Enums/TokenTypeEnum.cs
> +}
فایل جدا

2022-08-06 10:53 UTC, RAAvenger commented on Phase05/InvertedIndex/InvertedIndex.cs
> +        var @out = handler.HandleQuery(_queryBuilder.BuildQuery(queryTokenizer.Tokenize(query)));
نیازه متغییر گرفته بشه؟
مستقیم return بشه اوکی نیست؟

2022-08-06 10:53 UTC, RAAvenger commented on Phase05/InvertedIndex/QueryBuilder.cs
> +        var notWords = new List<string>();
نیازی به این لیستا هست؟
شما میتونید ایتم ها رو دونه دونه به همون سه تا لیستی که توی `Query` هست اضافه کنید

2022-08-09 06:46 UTC, M79Montazer approved these changes
Test data files should not be included in PR's.
other than that, its nicely done. good job :)

2022-08-11 13:58 UTC, nothatcreative5 commented on Phase05/InvertedIndex/InvertedIndex.cs
> +        var handler = new QueryHandler(engine);
کار اصلی سرچ با QueryHandler عه که اونجا داره توی کانستراکتور initialize میشه.

2022-08-11 14:55 UTC, nothatcreative5 commented on Phase05/InvertedIndex/Enums/TokenTypeEnum.cs
> +}
آخه کلاسی که زیرش تعریف شده extension عه و به نظرم خیلی عجیب و ناخوانا میشه اگه بخوام جداشون کنم.

2022-08-13 05:20 UTC, BozorgmehrZia requested changes

2022-08-13 05:20 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/TokenTypeTest.cs
> +        // Act
arrange نداره

2022-08-13 05:20 UTC, BozorgmehrZia commented on Phase05/InvertedIndex/QueryHandler.cs
> +        HashSet<string> set = new HashSet<string>(universalSet);
var

2022-08-14 04:32 UTC, BozorgmehrZia requested changes

2022-08-14 04:32 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/SearchEngineTest.cs
> +        var expected = new HashSet<string> { "1.txt", "2.txt" };
هر AAA توی تابع جدا باشه

2022-08-14 09:25 UTC, BozorgmehrZia approved these changes

2022-08-15 13:52 UTC, RAAvenger approved these changes
سلام
خسته نباشید

2022-08-15 15:00 UTC, merged