Cicd
Star-Academy/Summer1401-SE-Team08 pull request #5
Opened 2022-08-01 20:55 UTC by nothatcreative5

2022-08-02 10:20 UTC, BozorgmehrZia requested changes
اسم توابع تست مطابق چیزی که تتوی کارگاه گفته شده باشه
کامنتای AAA هم باید باشن

2022-08-02 10:20 UTC, BozorgmehrZia commented on Phase04/Folder.DotSettings.user
> +﻿<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-stora
اینو بزار توی gitignore

2022-08-02 10:20 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/FileReaderTest.cs
> +﻿// using InvertedIndex.Abstraction;
این چرا کامنته؟

2022-08-02 10:20 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/QueryBuilderTest.cs
> +    public void AndWords_Should_ContainNothing()
اسم تابع مطابق اون چیزی که توی کارگاه گفته شده باشه

2022-08-02 10:20 UTC, BozorgmehrZia commented on Phase05/InvertedIndex.Test/QueryHandlerTest.cs
> +        var engine = new Mock<ISearchEngine>();
توی اسمش mock هم باشه

2022-08-06 10:58 UTC, RAAvenger requested changes
سلام
خسته نباشید
معمولا action رو برای main میزنن
اگه خواستید دلیلش رو سر جلسه روزانه بپرسید

2022-08-06 10:58 UTC, RAAvenger commented on .github/workflows/buildPipeline.yml
> +        branches: ["CICD"]
`CICD` => `main`

2022-08-09 06:20 UTC, BozorgmehrZia reviewed
اسم توابع تست باید اینجوری باشه:
FolanTest_ShouldReturnBisar_WhenYeSharti

2022-08-10 05:50 UTC, mojo-izadi reviewed
It seems you have mastered the principle of single responsibility :)

2022-08-10 05:50 UTC, mojo-izadi commented on Phase05/Phase05-Console/Phase05-Console/Program.cs
> +        var path = @"C:\Users\Arya\OneDrive\Desktop\are\Summer1401-SE-Team08\Phase05-Console\EnglishData";
this code only works on one system because of the absolute path
try using a relative path instead

2022-08-10 05:50 UTC, mojo-izadi commented on Phase05/Phase05-Console/Phase05-Console/Program.cs
> +        var result = index.SearchDocsForQuery("God");
Why is your app like this?
The user is supposed to be able to make a query, not just see the result of a query you have made for them :)

2022-08-10 05:50 UTC, mojo-izadi commented on Phase05/InvertedIndex/Enums/TokenTypeEnum.cs
> +    }
Violates open close principle
What if a fourth type of word is added that needs to be handled differently?

2022-08-13 07:53 UTC, BozorgmehrZia requested changes

2022-08-13 07:53 UTC, BozorgmehrZia commented on Phase04/SimpleCalculator.Tests/OperatorProviderTest.cs
> +        // Arrange
arrange نباید جدا باشه

2022-08-13 07:53 UTC, BozorgmehrZia commented on Phase04/SimpleCalculator.Tests/OperatorProviderTest.cs
> +        // Act & Assert
چرا یکی شدن؟

2022-08-13 07:53 UTC, BozorgmehrZia commented on Phase04/SimpleCalculator.Tests/OperatorProviderTest.cs
> +        // Arrange
اگه اینام توی مرج درست میشن بیخیالشون شو

2022-08-13 20:04 UTC, nothatcreative5 commented on Phase04/SimpleCalculator.Tests/OperatorProviderTest.cs
> +        // Act & Assert
اینارو منتظرم جواب بگیرم درستش به چه صورته، تا اوکی کنم.

2022-08-14 04:33 UTC, BozorgmehrZia reviewed
اینم اگه میتونین فازای قبل نیان توی pr

2022-08-14 09:26 UTC, BozorgmehrZia approved these changes

2022-08-15 13:56 UTC, RAAvenger approved these changes
سلام
چرا اینهمه فایل تغییر کردن برای این فاز
اگه مرجش کنید چیزی نمیترکه؟

2022-08-15 15:15 UTC, merged