EFCore
Star-Academy/Summer1401-SE-Team08 pull request #6
Opened 2022-08-04 22:44 UTC by KhosroMoeini

2022-08-06 04:58 UTC, BozorgmehrZia requested changes
ساختار فایلا هم درست شن کل فاز 5 توی یه پوشه باشه

2022-08-06 04:58 UTC, BozorgmehrZia commented on Phase08/EFCore/Program.cs
> +        PathConfigurations pathConfigurations;
این جریانش چیه؟

2022-08-06 04:58 UTC, BozorgmehrZia commented on Phase08/EFCore/Program.cs
> +        List<Student> students;
چرا بالا تعریف شده؟

2022-08-06 04:58 UTC, BozorgmehrZia commented on Phase08/EFCore/Program.cs
> +            Average = database.Grades.Where(g => s.StudentNumber == g.StudentNumber).Select(g => g.Score).Average(),
توابع linq هرکدوم توی یه خط باشن

2022-08-06 04:58 UTC, BozorgmehrZia commented on Phase08/EFCore/Program.cs
> +        StudentDatabase database;
توی using باشه که وقتی کارتون تموم شد باهاش dispose بشه

2022-08-06 14:14 UTC, nothatcreative5 commented on Phase08/EFCore/Program.cs
> +        PathConfigurations pathConfigurations;
مکان فایل‌ها رو توی یک فایل .json ذخیره میکنیم.

2022-08-09 04:37 UTC, BozorgmehrZia commented on Phase08/EFCore/Program.cs
> +        PathConfigurations pathConfigurations;
نیازی به این کار نیست یه const باشه کافیه

2022-08-09 06:21 UTC, BozorgmehrZia reviewed
کامنتای قبلی درست شن

2022-08-11 12:52 UTC, BozorgmehrZia requested changes
فایل pathconf

2022-08-11 12:52 UTC, BozorgmehrZia commented on Phase08/EFCore/PathConfigurations.cs
> +public record PathConfigurations
این فایل رو پاک کن

2022-08-13 05:15 UTC, BozorgmehrZia reviewed
اسم توابع تست همچنان درست نیست

2022-08-14 04:27 UTC, BozorgmehrZia reviewed
اگه میشه فایلای فازای قبل نیان توی pr
قرار بود درست بشه

2022-08-14 04:28 UTC, BozorgmehrZia commented
> اگه میشه فایلای فازای قبل نیان توی pr

قرار بود درست بشه

2022-08-14 09:24 UTC, BozorgmehrZia approved these changes

2022-08-15 14:16 UTC, RAAvenger approved these changes
سلام
خسته نباشید

2022-08-15 14:16 UTC, RAAvenger commented on Phase08/EFCore/Database/StudentDatabase.cs
> +public class StudentDatabase : DbContext
مرسوم هست که این کلاس پسوند DbContext داشته باشه

2022-08-15 14:16 UTC, RAAvenger commented on Phase08/EFCore/Program.cs
> +        }
کاری که کردید اوکی هست ولی این رو بخونید:
https://stackoverflow.com/questions/1742940/why-not-catch-general-exceptions

2022-08-15 14:16 UTC, RAAvenger commented on Phase08/EFCore/Program.cs
> +        return topStudents;
جای اینکه متغییر بگیرید میتونید مستقیم برگردونید

2022-08-15 15:21 UTC, merged